export const ADD_EMPLOYEE="ADD_EMPLOYEE";
export const RETRIEVE_EMPLOYEE="RETRIEVE_EMPLOYEE";
export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEEADDRESSANDPHONENO="UPDATE_EMPLOYEEADDRESSANDPHONENO";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const RETRIEVE_EMPLOYEE_BY_ID="RETRIEVE_EMPLOYEE_BY_ID";

export const ADD_ASSET="ADD_ASSET";
export const RETRIEVE_ASSET="RETRIEVE_ASSET";
export const UPDATE_ASSET="UPDATE_ASSET";
export const DELETE_ASSET="DELETE_ASSET";